baseURL = "http://blog.jbc.dev"
title = "Joel B. Castillo"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

enableInlineShortcodes = true


[params]
    author = "Joel B. Castillo"
    description = ""
    keywords = "blog,developer,personal"
    info = "Tech Lead and DevSecOps Engineer"
    avatarURL = "images/avatar.jpg"
    # favicon_32 = "images/favicon.ico"
    # favicon_16 = "images/favicon.ico"
    footerContent = ""

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2021

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
	  childsrc = ["'self'"]
	  fontsrc = [
        "'self'",
		    "https://fonts.gstatic.com",
		    "https://cdn.jsdelivr.net/"
    ]
	  formaction = ["'self'"]
	  framesrc = ["'self'"]
	  imgsrc = ["'self'"]
	  objectsrc = ["'none'"]
	  stylesrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://fonts.googleapis.com/",
		    "https://cdn.jsdelivr.net/",
            "https://stackpath.bootstrapcdn.com/"
    ]
	  scriptsrc = [
        "'self'",
		    "'unsafe-inline'",
            "https://twemoji.maxcdn.com/",
            "https://identity.netlify.com/",
            "https://stackpath.bootstrapcdn.com"
    ]
	  prefetchsrc = ["'self'"]
      defaultsrc = [
          "'self'",
          "https://blog.jbc.dev/"
      ]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/joelbcastillo/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fa fa-twitter"
#     weight = 3
#     url = "https://twitter.com/joelbcastillo/"
[[params.social]]
    name = "Keybase"
    icon = "fa fa-keybase"
    weight = 4
    url = "https://keybase.io/joelbcastillo"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/joelbcastillo/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "https://blog.jbc.dev/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"
